//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationApp.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSchedule
    {
        public int StudentId { get; set; }
        public int CourseScheduleId { get; set; }
        public bool Enrolled { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual CourseSchedule CourseSchedule { get; set; }
    }
}
