//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationWeb.Client.RegistrationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegistrationServiceReference.IRegistrationService")]
    public interface IRegistrationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/RegisterForCourse", ReplyAction="http://tempuri.org/IRegistrationService/RegisterForCourseResponse")]
        bool RegisterForCourse(RegistrationWeb.Domain.RegistrationServiceReference.StudentDAO studentDAO, RegistrationWeb.Domain.RegistrationServiceReference.CourseScheduleDAO courseScheduleDAO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/RegisterForCourse", ReplyAction="http://tempuri.org/IRegistrationService/RegisterForCourseResponse")]
        System.Threading.Tasks.Task<bool> RegisterForCourseAsync(RegistrationWeb.Domain.RegistrationServiceReference.StudentDAO studentDAO, RegistrationWeb.Domain.RegistrationServiceReference.CourseScheduleDAO courseScheduleDAO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/HoldCourse", ReplyAction="http://tempuri.org/IRegistrationService/HoldCourseResponse")]
        bool HoldCourse(RegistrationWeb.Domain.RegistrationServiceReference.StudentDAO studentDAO, RegistrationWeb.Domain.RegistrationServiceReference.CourseScheduleDAO courseScheduleDAO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/HoldCourse", ReplyAction="http://tempuri.org/IRegistrationService/HoldCourseResponse")]
        System.Threading.Tasks.Task<bool> HoldCourseAsync(RegistrationWeb.Domain.RegistrationServiceReference.StudentDAO studentDAO, RegistrationWeb.Domain.RegistrationServiceReference.CourseScheduleDAO courseScheduleDAO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/DropCourse", ReplyAction="http://tempuri.org/IRegistrationService/DropCourseResponse")]
        bool DropCourse(RegistrationWeb.Domain.RegistrationServiceReference.StudentDAO studentDAO, RegistrationWeb.Domain.RegistrationServiceReference.StudentScheduleDAO studentScheduleDAO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/DropCourse", ReplyAction="http://tempuri.org/IRegistrationService/DropCourseResponse")]
        System.Threading.Tasks.Task<bool> DropCourseAsync(RegistrationWeb.Domain.RegistrationServiceReference.StudentDAO studentDAO, RegistrationWeb.Domain.RegistrationServiceReference.StudentScheduleDAO studentScheduleDAO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/ListStudentSchedule", ReplyAction="http://tempuri.org/IRegistrationService/ListStudentScheduleResponse")]
        RegistrationWeb.Domain.RegistrationServiceReference.CourseScheduleDAO[] ListStudentSchedule(int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/ListStudentSchedule", ReplyAction="http://tempuri.org/IRegistrationService/ListStudentScheduleResponse")]
        System.Threading.Tasks.Task<RegistrationWeb.Domain.RegistrationServiceReference.CourseScheduleDAO[]> ListStudentScheduleAsync(int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/ListStudents", ReplyAction="http://tempuri.org/IRegistrationService/ListStudentsResponse")]
        RegistrationWeb.Domain.RegistrationServiceReference.StudentDAO[] ListStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationService/ListStudents", ReplyAction="http://tempuri.org/IRegistrationService/ListStudentsResponse")]
        System.Threading.Tasks.Task<RegistrationWeb.Domain.RegistrationServiceReference.StudentDAO[]> ListStudentsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistrationServiceChannel : RegistrationWeb.Client.RegistrationServiceReference.IRegistrationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrationServiceClient : System.ServiceModel.ClientBase<RegistrationWeb.Client.RegistrationServiceReference.IRegistrationService>, RegistrationWeb.Client.RegistrationServiceReference.IRegistrationService {
        
        public RegistrationServiceClient() {
        }
        
        public RegistrationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegisterForCourse(RegistrationWeb.Domain.RegistrationServiceReference.StudentDAO studentDAO, RegistrationWeb.Domain.RegistrationServiceReference.CourseScheduleDAO courseScheduleDAO) {
            return base.Channel.RegisterForCourse(studentDAO, courseScheduleDAO);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterForCourseAsync(RegistrationWeb.Domain.RegistrationServiceReference.StudentDAO studentDAO, RegistrationWeb.Domain.RegistrationServiceReference.CourseScheduleDAO courseScheduleDAO) {
            return base.Channel.RegisterForCourseAsync(studentDAO, courseScheduleDAO);
        }
        
        public bool HoldCourse(RegistrationWeb.Domain.RegistrationServiceReference.StudentDAO studentDAO, RegistrationWeb.Domain.RegistrationServiceReference.CourseScheduleDAO courseScheduleDAO) {
            return base.Channel.HoldCourse(studentDAO, courseScheduleDAO);
        }
        
        public System.Threading.Tasks.Task<bool> HoldCourseAsync(RegistrationWeb.Domain.RegistrationServiceReference.StudentDAO studentDAO, RegistrationWeb.Domain.RegistrationServiceReference.CourseScheduleDAO courseScheduleDAO) {
            return base.Channel.HoldCourseAsync(studentDAO, courseScheduleDAO);
        }
        
        public bool DropCourse(RegistrationWeb.Domain.RegistrationServiceReference.StudentDAO studentDAO, RegistrationWeb.Domain.RegistrationServiceReference.StudentScheduleDAO studentScheduleDAO) {
            return base.Channel.DropCourse(studentDAO, studentScheduleDAO);
        }
        
        public System.Threading.Tasks.Task<bool> DropCourseAsync(RegistrationWeb.Domain.RegistrationServiceReference.StudentDAO studentDAO, RegistrationWeb.Domain.RegistrationServiceReference.StudentScheduleDAO studentScheduleDAO) {
            return base.Channel.DropCourseAsync(studentDAO, studentScheduleDAO);
        }
        
        public RegistrationWeb.Domain.RegistrationServiceReference.CourseScheduleDAO[] ListStudentSchedule(int studentId) {
            return base.Channel.ListStudentSchedule(studentId);
        }
        
        public System.Threading.Tasks.Task<RegistrationWeb.Domain.RegistrationServiceReference.CourseScheduleDAO[]> ListStudentScheduleAsync(int studentId) {
            return base.Channel.ListStudentScheduleAsync(studentId);
        }
        
        public RegistrationWeb.Domain.RegistrationServiceReference.StudentDAO[] ListStudents() {
            return base.Channel.ListStudents();
        }
        
        public System.Threading.Tasks.Task<RegistrationWeb.Domain.RegistrationServiceReference.StudentDAO[]> ListStudentsAsync() {
            return base.Channel.ListStudentsAsync();
        }
    }
}
